YOUTUBE_DEFAULT_RTMP_BASE = "rtmp://a.rtmp.youtube.com/live2"
YOUTUBE_API_BASE = "https://www.googleapis.com/youtube/v3"
CHAT_PROMPT_OFFSET_FRAMES = 30

SILENT_AUDIO_SAMPLE_RATE = 48_000
SILENT_AUDIO_CHANNELS = 2
SILENT_AUDIO_FRAME_MS = 20
